name: ai_resume_generator
description: AI Resume & Cover Letter Generator with AdMob & Premium

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  provider: ^6.0.5
  google_mobile_ads: ^3.0.0
  in_app_purchase: ^3.1.7
  in_app_purchase_android: ^0.3.0+15
  in_app_purchase_storekit: ^0.3.7+1
  flutter_dotenv: ^5.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.1
  timeago: ^3.6.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/images/templates/
