# Test Configuration for Form Validation
test_scenarios:
  validation_tests:
    - name: "Basic Validation"
      description: "Test basic field validation rules"
      fields:
        - name
        - email
        - phone
        - position
        - contact
    
    - name: "Security Validation"
      description: "Test security-related validation"
      attacks:
        - xss
        - sql_injection
        - html_injection
        - command_injection
        - path_traversal
    
    - name: "Performance Validation"
      description: "Test validation performance"
      metrics:
        - execution_time
        - memory_usage
        - throughput

  integration_tests:
    - name: "Form Submission"
      description: "Test complete form submission flow"
      screens:
        - input_screen
        - template_editor
        - api_key_setup
        - settings_screen
    
    - name: "Error Handling"
      description: "Test error handling and user feedback"
      scenarios:
        - invalid_input
        - network_errors
        - validation_failures

  security_tests:
    - name: "Input Sanitization"
      description: "Test input sanitization effectiveness"
      attack_vectors:
        - script_injection
        - html_injection
        - sql_injection
        - command_injection
        - path_traversal
        - ldap_injection
        - nosql_injection
        - buffer_overflow
        - unicode_attacks
        - encoding_attacks
